import { ArrowLeft, MessageCircle, Send } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { api } from '../services/api'

function ChatsPage() {
  const { token, user } = useAuth(); const [params] = useSearchParams(); const [conversations, setConversations] = useState([]); const [active, setActive] = useState(null); const [messages, setMessages] = useState([]); const [draft, setDraft] = useState(''); const [error, setError] = useState(''); const [starting, setStarting] = useState(Boolean(params.get('listingId')))
  const loadConversations = useCallback(() => api('/conversations', { token }).then(({ conversations: items }) => { setConversations(items); return items }).catch((err) => setError(err.message)), [token])
  const listingId = params.get('listingId')
  useEffect(() => { loadConversations().then(async (items) => { if (listingId) { try { const data = await api('/conversations', { method: 'POST', token, body: { listingId } }); const latest = [data.conversation, ...items.filter((item) => item.id !== data.conversation.id)]; setConversations(latest); setActive(data.conversation) } catch (err) { setError(err.message) } finally { setStarting(false) } } else if (items?.length) setActive(items[0]) }) }, [listingId, loadConversations, token])
  useEffect(() => { if (!active) return; api(`/conversations/${active.id}/messages`, { token }).then(({ messages: items }) => setMessages(items)).catch((err) => setError(err.message)) }, [active, token])
  const send = async (event) => { event.preventDefault(); const text = draft.trim(); if (!text || !active) return; try { const data = await api(`/conversations/${active.id}/messages`, { method: 'POST', token, body: { text } }); setMessages([...messages, data.data]); setDraft(''); setConversations(conversations.map((item) => item.id === active.id ? { ...item, lastMessageText: text, lastMessageAt: data.data.createdAt } : item)) } catch (err) { setError(err.message) } }
  return <section className="chats-page"><div className="chats-heading"><div><span className="eyebrow">YOUR CONVERSATIONS</span><h1>Messages</h1></div>{active && <Link to={`/listings/${active.listing.id}`} className="back-link"><ArrowLeft size={16} /> View listing</Link>}</div>{error && <p className="form-error">{error}</p>}{starting ? <div className="empty-results"><p>Opening your conversation…</p></div> : <div className="chat-layout"><aside className="conversation-list">{conversations.length ? conversations.map((conversation) => <button key={conversation.id} className={active?.id === conversation.id ? 'active' : ''} onClick={() => setActive(conversation)}><span className="conversation-avatar">{conversation.otherUser.name.slice(0, 1)}</span><span><strong>{conversation.otherUser.name}</strong><small>{conversation.listing.title}</small><em>{conversation.lastMessageText || 'Start the conversation'}</em></span></button>) : <div className="conversation-empty"><MessageCircle size={28} /><p>No conversations yet.</p><Link to="/explore">Explore listings</Link></div>}</aside><main className="message-panel">{active ? <><header><span className="conversation-avatar">{active.otherUser.name.slice(0, 1)}</span><div><strong>{active.otherUser.name}</strong><small>About {active.listing.title}</small></div></header><div className="messages">{messages.length ? messages.map((message) => <p key={message.id} className={String(message.sender) === String(user.id) ? 'own-message' : ''}>{message.text}</p>) : <div className="message-empty">Say hello and ask whether this item is still available.</div>}</div><form className="message-form" onSubmit={send}><input value={draft} onChange={(event) => setDraft(event.target.value)} maxLength="1000" placeholder="Write a message…" /><button aria-label="Send message"><Send size={18} /></button></form></> : <div className="message-empty">Choose a conversation to read messages.</div>}</main></div>}</section>
}
export default ChatsPage
