import { LogOut, Pencil, Star } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { api } from '../services/api'
import { getListings } from '../services/listings'
import ListingCard from '../components/ListingCard'

function ProfilePage() {
  const { token, user, updateUser, logout } = useAuth(); const [profile, setProfile] = useState(null); const [items, setItems] = useState([]); const [editing, setEditing] = useState(false); const [form, setForm] = useState({}); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { api('/profile/me', { token }).then(({ profile: data }) => { setProfile(data); setForm({ name: data.name, avatarUrl: data.avatarUrl || '', hostel: data.hostel || '', department: data.department || '', year: data.year || '' }) }).catch((err) => setError(err.message)); getListings().then((listings) => setItems(listings.filter((item) => item.seller?.id === user.id || item.seller === user.name))) }, [token, user.id, user.name])
  const save = async (event) => { event.preventDefault(); setError(''); try { const data = await api('/profile/me', { method: 'PATCH', token, body: { ...form, year: form.year === '' ? null : Number(form.year) } }); setProfile(data.profile); updateUser(data.profile); setMessage(data.message); setEditing(false) } catch (err) { setError(err.message) } }
  if (!profile && !error) return <section className="detail-state"><h1>Loading your profile…</h1></section>
  if (error && !profile) return <section className="detail-state"><h1>{error}</h1></section>
  return <section className="profile-page"><div className="profile-header"><div className="profile-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" /> : profile.name.slice(0, 1)}</div><div><span className="eyebrow">VERIFIED STUDENT</span><h1>{profile.name}</h1><p>{profile.department || 'Add your department'} {profile.year ? `· Year ${profile.year}` : ''}</p><p className="profile-email">{profile.email}</p></div><button className="outline-button" onClick={() => setEditing(!editing)}><Pencil size={16} /> {editing ? 'Cancel' : 'Edit profile'}</button></div>{message && <p className="form-success">{message}</p>}{error && <p className="form-error">{error}</p>}{editing && <form className="profile-form form-stack" onSubmit={save}><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Avatar image URL <small>Optional</small><input type="url" value={form.avatarUrl} onChange={(event) => setForm({ ...form, avatarUrl: event.target.value })} placeholder="https://..." /></label><div className="form-row"><label>Department<input value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} /></label><label>Year<select value={form.year} onChange={(event) => setForm({ ...form, year: event.target.value })}><option value="">Not specified</option>{[1,2,3,4,5,6,7,8].map((year) => <option key={year} value={year}>{year}</option>)}</select></label></div><label>Hostel <small>Optional</small><input value={form.hostel} onChange={(event) => setForm({ ...form, hostel: event.target.value })} /></label><button className="primary-button">Save changes</button></form>}<section className="profile-stats"><div><strong>{items.length}</strong><span>Active listings</span></div><div><strong><Star size={17} fill="currentColor" /> {profile.ratings.average.toFixed(1)}</strong><span>{profile.ratings.count ? `${profile.ratings.count} ratings` : 'No ratings yet'}</span></div><div><strong>{profile.hostel || 'Campus'}</strong><span>Pickup area</span></div></section><div className="section-heading"><div><span className="eyebrow">YOUR SELLING</span><h2>Active listings</h2></div><Link to="/sell">Sell another item</Link></div>{items.length ? <div className="listing-grid">{items.map((item) => <ListingCard key={item.id} listing={item} />)}</div> : <div className="empty-results"><h2>You have not listed anything yet</h2><p>Your next unused item could be exactly what another student needs.</p><Link className="primary-button" to="/sell">Create a listing</Link></div>}<button className="logout-link desktop-logout" onClick={logout}><LogOut size={16} /> Sign out</button></section>
}
export default ProfilePage
